// <auto-generated />
using System;
using AppointmentScheduling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentScheduling.Api.Data.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260826161353_AddPublicBookingReferences")]
    partial class AddPublicBookingReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AppointmentSlot", b =>
                {
                    b.Property<int>("AppointmentSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailabilitySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentSlotId");

                    b.HasIndex("AvailabilitySessionId", "StartsAtUtc")
                        .IsUnique();

                    b.ToTable("AppointmentSlots", t =>
                        {
                            t.HasCheckConstraint("CK_AppointmentSlots_TimeRange", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.Property<int>("AvailabilitySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AvailabilitySessionId");

                    b.HasIndex("ClinicianId", "StartsAtUtc");

                    b.ToTable("AvailabilitySessions", t =>
                        {
                            t.HasCheckConstraint("CK_AvailabilitySessions_SlotDurationMinutes", "\"SlotDurationMinutes\" > 0");

                            t.HasCheckConstraint("CK_AvailabilitySessions_TimeRange", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.HasIndex("AppointmentSlotId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("PatientId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Cancellation", "(\"Status\" = 'Active' AND \"CancelledAtUtc\" IS NULL) OR (\"Status\" = 'Cancelled' AND \"CancelledAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Bookings_Status", "\"Status\" IN ('Active', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Clinician", b =>
                {
                    b.Property<int>("ClinicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClinicianId");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            ClinicianId = 1,
                            IsActive = true,
                            Name = "Dr Maya Patel",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 2,
                            IsActive = true,
                            Name = "Dr Daniel Brooks",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 3,
                            IsActive = false,
                            Name = "Dr Sofia Ahmed",
                            Role = "General Practitioner"
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.UnavailablePeriod", b =>
                {
                    b.Property<int>("UnavailablePeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UnavailablePeriodId");

                    b.HasIndex("ClinicianId", "StartsAtUtc");

                    b.ToTable("UnavailablePeriods", t =>
                        {
                            t.HasCheckConstraint("CK_UnavailablePeriods_TimeRange", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AppointmentSlot", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.AvailabilitySession", "AvailabilitySession")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("AvailabilitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilitySession");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.Clinician", "Clinician")
                        .WithMany("AvailabilitySessions")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Booking", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.AppointmentSlot", "AppointmentSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("AppointmentSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentScheduling.Api.Models.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentSlot");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.UnavailablePeriod", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.Clinician", "Clinician")
                        .WithMany("UnavailablePeriods")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AppointmentSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.Navigation("AppointmentSlots");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Clinician", b =>
                {
                    b.Navigation("AvailabilitySessions");

                    b.Navigation("UnavailablePeriods");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Patient", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
