// <auto-generated />
using System;
using AppointmentScheduling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentScheduling.Api.Data.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260813162857_AddAvailabilityDomain")]
    partial class AddAvailabilityDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AppointmentSlot", b =>
                {
                    b.Property<int>("AppointmentSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailabilitySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentSlotId");

                    b.HasIndex("AvailabilitySessionId", "StartsAtUtc")
                        .IsUnique();

                    b.ToTable("AppointmentSlots", t =>
                        {
                            t.HasCheckConstraint("CK_AppointmentSlots_TimeRange", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.Property<int>("AvailabilitySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AvailabilitySessionId");

                    b.HasIndex("ClinicianId", "StartsAtUtc");

                    b.ToTable("AvailabilitySessions", t =>
                        {
                            t.HasCheckConstraint("CK_AvailabilitySessions_SlotDurationMinutes", "\"SlotDurationMinutes\" > 0");

                            t.HasCheckConstraint("CK_AvailabilitySessions_TimeRange", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Clinician", b =>
                {
                    b.Property<int>("ClinicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClinicianId");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            ClinicianId = 1,
                            IsActive = true,
                            Name = "Dr Maya Patel",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 2,
                            IsActive = true,
                            Name = "Dr Daniel Brooks",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 3,
                            IsActive = false,
                            Name = "Dr Sofia Ahmed",
                            Role = "General Practitioner"
                        });
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AppointmentSlot", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.AvailabilitySession", "AvailabilitySession")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("AvailabilitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilitySession");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.HasOne("AppointmentScheduling.Api.Models.Clinician", "Clinician")
                        .WithMany("AvailabilitySessions")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.AvailabilitySession", b =>
                {
                    b.Navigation("AppointmentSlots");
                });

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Clinician", b =>
                {
                    b.Navigation("AvailabilitySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
