// <auto-generated />
using AppointmentScheduling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentScheduling.Api.Data.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260806000051_SeedInitialClinicians")]
    partial class SeedInitialClinicians
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AppointmentScheduling.Api.Models.Clinician", b =>
                {
                    b.Property<int>("ClinicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClinicianId");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            ClinicianId = 1,
                            IsActive = true,
                            Name = "Dr Maya Patel",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 2,
                            IsActive = true,
                            Name = "Dr Daniel Brooks",
                            Role = "General Practitioner"
                        },
                        new
                        {
                            ClinicianId = 3,
                            IsActive = false,
                            Name = "Dr Sofia Ahmed",
                            Role = "General Practitioner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
